### PR TITLE
Split off functionality that relies on libm

### PR DESCRIPTION
**Pull request by andreittr**
Previously some parts of compiler-rt depended on functions provided by a math library, commonly supplied together with a real libc. This change sections off the parts dependent on libm, allowing a minimal compiler-rt to be built with nolibc alone.

### CODE REVIEW

**Review by StefanJum — COMMENTED** [review]
This looks fine @andreittr, thank you.

`allowing a minimal compiler-rt to be built with nolibc alone` What is the minimal setup for building `compiler-rt` with this pr? I suppose `libunwind` it's still needed, right?

**Comment by andreittr** [comment]
> What is the minimal setup for building `compiler-rt` with this pr? I suppose `libunwind` it's still needed, right?

Nope, following the merging of https://github.com/unikraft/lib-compiler-rt/pull/14 libunwind is no longer needed, except if you _really_ want that gcc_personality_v0. A plainly configured `compiler-rt` should build with no external dependencies.

also: rebased on top of staging, fixed conflicts & re-pushed.

**Review by StefanJum — APPROVED** [review]
Thank you @andreittr, all good.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
